# Copyright (C) 2011 Sergey Yanovich <ynvich@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.
#
# Please see ./COPYING for details
# app/config/application.yml

defaults: &defaults
  root:
    password: 123456

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
